services:
  directus:
    image: directus/directus:11.1.1
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      SECRET: "fdsfas89435hj3kh#h"
      ADMIN_EMAIL: "tomasz13nocon@gmail.com"
      ADMIN_PASSWORD: "qweqwe"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      QUERY_LIMIT_DEFAULT: "-1"
