name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment webhook
        env:
          DEPLOY_PREVIEW_URL: ${{ secrets.DEPLOY_PREVIEW_URL }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          curl -X POST "$DEPLOY_PREVIEW_URL" \
            -H "Content-Type: application/json" \
            -d "{\"token\": \"$DEPLOY_TOKEN\"}"
